[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "kandc-dev"                 # <-- only change
version = "0.0.29.dev0"             # use PEP 440 pre/dev versions for clarity
description = "Keys & Caches - GPU profiling and tracing library (DEV)"
readme = "README.md"
license = {text = "MIT"}
authors = [{name = "Herdora", email = "contact@herdora.com"}]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
]
requires-python = ">=3.8,<3.14"
dependencies = [
    "requests>=2.25.0",
    "torch>=2.0.0",
    "numpy>=1.21.0",
    "packaging>=21.0",
]

[project.optional-dependencies]
dev = ["pytest>=6.0","ruff>=0.1.0"]

[project.urls]
Homepage = "https://github.com/Herdora/kandc"
Repository = "https://github.com/Herdora/kandc.git"
Issues = "https://github.com/Herdora/kandc/issues"

[tool.setuptools.packages.find]
where = ["src"]

[tool.ruff]
line-length = 100
target-version = "py38"

[tool.ruff.lint]
select = ["E", "F"]
ignore = ["E203"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
