DEFAULT_TRACE_ACTIVITIES = ["CPU", "CUDA"]
MINIMUM_PACKAGES = ["torch", "requests"]
ENV_CACHY_ENABLED = "CACHY_ENABLED"

TRACE_DIR = "traces"
REPO_NAME = "chisel"

CHISEL_BACKEND_RUN_ENV_KEY = "CHISEL_BACKEND_RUN"
CHISEL_JOB_ID_ENV_KEY = "CHISEL_JOB_ID"
CHISEL_API_KEY_ENV_KEY = "CHISEL_API_KEY"
CHISEL_BACKEND_URL_ENV_KEY = "CHISEL_BACKEND_URL"

CHISEL_BACKEND_URL = "http://localhost:8000"
