#!/bin/bash

echo "🔧 Keys & Caches Development Mode"
echo ""
echo "Development mode is now controlled by editing the DEV_MODE constant in:"
echo "  kandc/src/kandc/constants.py"
echo ""
echo "To switch modes:"
echo "  • Set DEV_MODE = True  for development (localhost URLs)"
echo "  • Set DEV_MODE = False for production (keysandcaches.com URLs)"
echo ""
echo "Current configuration:"
echo "  Run 'kandc config' to see current settings"
echo ""
echo "💡 This is much simpler than environment variables!"
